prgrms-be-devcourse/NBE6-8-2-Team07

- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-prod.yml
- backend/src/main/resources/application.yml
> chore: h2 초기 세팅

- backend/src/main/java/com/back/fairytale/domain/user/controller/UserController.java
- backend/src/main/java/com/back/fairytale/domain/user/entity/User.java
- backend/src/main/java/com/back/fairytale/domain/user/enums/IsDeleted.java
- backend/src/main/java/com/back/fairytale/domain/user/enums/Role.java
- backend/src/main/java/com/back/fairytale/domain/user/repository/UserRepository.java
- 유저 엔티티와 엔티티에 필요한 enum, 레포지토리를 구현하였습니다.
Close #15
> [Feat] 유저 엔티티 정의

- backend/src/main/java/com/back/fairytale/bookmark/controller/BookMarkController.java
- backend/src/main/java/com/back/fairytale/bookmark/entity/BookMark.java
- backend/src/main/java/com/back/fairytale/domain/keyword/entity/Keyword.java
- backend/src/main/java/com/back/fairytale/domain/keyword/enums/KeywordType.java
- backend/src/main/java/com/back/fairytale/domain/user/entity/User.java
> refactor: 패키지 이동 및 클래스명 변경 (#27)

- backend/src/main/java/com/back/fairytale/domain/bookmark/controller/BookMarkController.java
- backend/src/main/java/com/back/fairytale/domain/bookmark/entity/BookMark.java
- backend/src/main/java/com/back/fairytale/domain/user/entity/User.java
> refactor: 패키지 이동 (#29)

- backend/src/main/java/com/back/fairytale/domain/keyword/controller/KeywordController.java
- backend/src/main/java/com/back/fairytale/domain/keyword/dto/KeywordRequestDto.java
- backend/src/main/java/com/back/fairytale/domain/keyword/dto/KeywordResponseDto.java
- backend/src/main/java/com/back/fairytale/domain/keyword/repository/KeywordRepository.java
- backend/src/main/java/com/back/fairytale/domain/keyword/service/KeywordService.java
> [Feat] keyword 관련 클래스 틀 생성 (Enhancement/21)

- backend/src/main/java/com/back/fairytale/domain/bookmark/controller/BookMarkController.java
- backend/src/main/java/com/back/fairytale/domain/bookmark/dto/BookMarkDto.java
- backend/src/main/java/com/back/fairytale/domain/bookmark/exception/BookMarkAlreadyExistsException.java
- backend/src/main/java/com/back/fairytale/domain/bookmark/exception/BookMarkNotFoundException.java
- backend/src/main/java/com/back/fairytale/domain/bookmark/repository/BookMarkRepository.java
- backend/src/main/java/com/back/fairytale/domain/bookmark/service/BookMarkService.java
- backend/src/main/java/com/back/fairytale/domain/fairytale/repository/FairytaleRepository.java
- backend/src/main/java/com/back/fairytale/global/security/SecurityConfig.java
- backend/src/test/java/com/back/fairytale/domain/bookmark/service/BookMarkServiceTest.java
> [feat] 즐겨찾기 기능 구현 #14

- backend/src/main/java/com/back/fairytale/global/config/RestTemplateConfig.java
> fix: @Configuration 누락

- backend/src/main/java/com/back/fairytale/domain/fairytale/controller/FairytaleController.java
- backend/src/main/java/com/back/fairytale/domain/fairytale/dto/FairytaleCreateRequest.java
- backend/src/main/java/com/back/fairytale/domain/fairytale/dto/FairytaleResponse.java
- backend/src/main/java/com/back/fairytale/domain/fairytale/entity/Fairytale.java
- backend/src/main/java/com/back/fairytale/domain/fairytale/service/FairytaleService.java
- backend/src/main/java/com/back/fairytale/domain/keyword/entity/Keyword.java
- backend/src/main/java/com/back/fairytale/domain/keyword/repository/KeywordRepository.java
- backend/src/main/java/com/back/fairytale/domain/user/entity/User.java
- backend/src/main/java/com/back/fairytale/global/security/CustomOAuth2User.java
- backend/src/main/resources/application-test.yml
- backend/src/test/java/com/back/fairytale/domain/fairytale/controller/FairytaleControllerTest.java
Close #35 
동화 생성 구현했습니다. 테스트 코드 돌려보시고 확인해주세요.
지금 하드코딩된 데이터도 있어서 코드가 많이 지저분한데, 리팩토링 하겠습니다.
> 동화 생성 구현 (테스트 코드)

- backend/src/main/java/com/back/fairytale/domain/bookmark/controller/BookMarkController.java
- backend/src/main/java/com/back/fairytale/domain/bookmark/service/BookMarkService.java
- backend/src/main/java/com/back/fairytale/global/security/CustomOAuth2User.java
> [refactor] 기존 User -> CustomOAuth2User로 변경

- backend/src/main/java/com/back/fairytale/domain/bookmark/entity/BookMark.java
- backend/src/main/java/com/back/fairytale/domain/like/entity/Like.java
> [chore] 테이블 이름 변경

- backend/src/main/java/com/back/fairytale/domain/fairytale/controller/FairytaleController.java
- backend/src/main/java/com/back/fairytale/domain/fairytale/dto/FairytaleCreateRequest.java
- backend/src/main/java/com/back/fairytale/domain/fairytale/entity/Fairytale.java
- backend/src/main/java/com/back/fairytale/domain/fairytale/exception/UserNotFoundException.java
- backend/src/main/java/com/back/fairytale/domain/fairytale/service/FairytaleService.java
- backend/src/main/java/com/back/fairytale/external/ai/client/GeminiClient.java
- backend/src/main/java/com/back/fairytale/external/ai/dto/GeminiRequest.java
- backend/src/main/java/com/back/fairytale/external/ai/dto/GeminiResponse.java
- backend/src/main/java/com/back/fairytale/external/exception/GeminiApiException.java
- backend/src/test/java/com/back/fairytale/domain/fairytale/controller/FairytaleControllerTest.java
Close #54
테스트 코드 추가, 에러 처리, 중복코드 제거
> 리팩토링, 테스트 코드 추가

- backend/src/main/java/com/back/fairytale/domain/bookmark/controller/BookMarkController.java
- backend/src/main/java/com/back/fairytale/domain/bookmark/service/BookMarkService.java
- backend/src/main/java/com/back/fairytale/domain/like/controller/LikeController.java
- backend/src/main/java/com/back/fairytale/domain/like/service/LikeService.java
Close #63 
* 컨트롤러에서 DTO를 생성하는 방식은, 컨트롤러가 비즈니스 로직을 너무 많이 알아야 하기 때문에 권장되지 않는다.
* 이 방식은 테스트와 유지보수가 어렵다는 단점도 있다.
</br>
* 처음에는 직관적이고, 서비스에 명확하게 데이터를 전달하기 위해 컨트롤러 단에서 DTO를 생성했지만, 이는 권장되지 않는 방식이었다.
* 코드가 깔끔하지 않는 문제도 있다.. 클린 코드를 작성하자..
> [Refactor] 컨트롤러 DTO 제거

- backend/src/main/java/com/back/fairytale/domain/keyword/controller/KeywordController.java
- backend/src/main/java/com/back/fairytale/domain/keyword/entity/Keyword.java
- backend/src/main/java/com/back/fairytale/domain/keyword/service/KeywordService.java
- backend/src/test/java/com/back/fairytale/domain/keyword/controller/KeywordControllerTest.java
키워드단건(특정) 조회 기능 구현 완료했습니다.
테스트 성공했습니다
> [Feat] 특정키워드 조회 구현  

- backend/src/main/java/com/back/fairytale/domain/bookmark/dto/BookMarkDto.java
- backend/src/main/java/com/back/fairytale/domain/bookmark/entity/BookMark.java
- backend/src/main/java/com/back/fairytale/domain/bookmark/service/BookMarkService.java
- backend/src/main/java/com/back/fairytale/domain/like/dto/LikeDto.java
- backend/src/main/java/com/back/fairytale/domain/like/entity/Like.java
- backend/src/main/java/com/back/fairytale/domain/like/service/LikeService.java
> [Feat] 사용자가 좋아요/즐겨찾기를 누른 동화인지 확인하는 로직 구현

- backend/src/main/java/com/back/fairytale/domain/fairytale/controller/FairytaleController.java
- backend/src/main/java/com/back/fairytale/domain/fairytale/dto/FairytaleDetailResponse.java
- backend/src/main/java/com/back/fairytale/domain/fairytale/repository/FairytaleRepository.java
- backend/src/main/java/com/back/fairytale/domain/fairytale/service/FairytaleService.java
- backend/src/main/java/com/back/fairytale/external/ai/client/GeminiClient.java
- backend/src/test/java/com/back/fairytale/domain/fairytale/controller/FairytaleControllerTest.java
Close #69 
동화 상세 정보 조회 기능 구현했습니다.
현재 로그인되어 있는 사용자의 동화를 조회할 수 있도록 수정하였습니다.
> 동화 상세 정보 조회

- backend/src/main/java/com/back/fairytale/domain/fairytale/controller/FairytaleController.java
- backend/src/main/java/com/back/fairytale/domain/fairytale/service/FairytaleService.java
- backend/src/main/java/com/back/fairytale/domain/keyword/entity/Keyword.java
- backend/src/test/java/com/back/fairytale/domain/fairytale/controller/FairytaleControllerTest.java
Close #74 
동화 삭제 기능 구현하고 테스트도 통과했습니다.
테스트 코드 리팩토링 했습니다.
> 동화 삭제 기능 구현

- .idea/dataSources.xml
- frontend/package-lock.json
- frontend/package.json
- frontend/src/app/fairytale/get/page.tsx
- frontend/src/app/fairytale/read/page.tsx
- frontend/src/context/fairytaleContext.tsx
- frontend/src/context/favoriteContext.tsx
- frontend/src/context/keywordContext.tsx
- frontend/src/context/likeContext.tsx
- frontend/src/context/usersContext.tsx
Close #71
동화조회페이지와 동화읽기창의 UI구현
> [Feat] 동화조회페이지 UI구현

- backend/build.gradle.kts
- backend/src/main/java/com/back/fairytale/global/springDoc/SpringDocConfig.java
Close #82 
API 문서 자동화
엔드포인트 -> http://localhost:8080/swagger-ui/index.html
> 스웨거 API 문서 자동화

- backend/src/main/java/com/back/fairytale/domain/keyword/controller/KeywordController.java
- backend/src/main/java/com/back/fairytale/domain/keyword/entity/Keyword.java
- backend/src/main/java/com/back/fairytale/domain/keyword/service/KeywordService.java
- backend/src/test/java/com/back/fairytale/domain/keyword/service/KeywordServiceTest.java
> [Feat] 키워드 삭제 기능 구현

- backend/src/main/java/com/back/fairytale/domain/keyword/controller/KeywordController.java
- backend/src/main/java/com/back/fairytale/domain/keyword/entity/Keyword.java
- backend/src/main/java/com/back/fairytale/domain/keyword/service/KeywordService.java
낙관적 락 사용
useage_count 필드 안전하게 증가하도록 엔티티와 서비스 로직 수정완료
> [Refactor] 동시성 문제 해결

- README.md
- frontend/src/app/globals.css
- frontend/src/app/introduction/page.tsx
- frontend/src/app/introduction/project/page.tsx
- frontend/src/app/introduction/service/page.tsx
- frontend/src/app/layout.tsx
Close #101 
CSS폰트오류수정을 하였습니다.
소개페이지 문구 추가하였습니다.
> CSS폰트오류수정 및 소개페이지 문구 추가

- backend/src/test/java/com/back/fairytale/domain/user/controller/UserControllerTest.java
- backend/src/test/java/com/back/fairytale/domain/user/service/AuthServiceTest.java
메서드 변경에 따라 UserControllerTest, AuthServiceTest 코드를 수정하였습니다.
Close #111
> [Fix]: 토큰 검증 테스트 수정

- backend/src/main/java/com/back/fairytale/domain/fairytale/entity/Fairytale.java
- frontend/src/app/fairytale/get/page.tsx
Close #104 
동화 삭제 기능 추가하고 백엔드랑 연결했습니다.
뷰모드 그리드모드로 동화를 조회할 수 있도록 수정했습니다.
> 프론트엔드 동화 삭제 추가

- backend/src/main/java/com/back/fairytale/domain/fairytale/service/FairytaleService.java
Close #120
동화 생성 내용이 이상해서 봤더니 코드에 오류가 있어 수정했습니다.
> buildPrompt 오류 수정

- backend/src/main/java/com/back/fairytale/domain/fairytale/service/FairytaleService.java
Close #119 
동화를 생성할 때 키워드 usage_count 증가
> 동화 생성 시 키워드 사용 횟수 증가

- frontend/src/app/fairytale/get/[id]/page.tsx
- frontend/src/app/fairytale/get/page.tsx
- frontend/src/context/fairytaleContext.tsx
Close #106 
- 즐겨찾기 목록, 버튼 추가
- credentials: 'include' 인증 정보 포함
> 즐겨찾기 목록, 버튼 추가

- backend/src/main/java/com/back/BackendApplication.java
- backend/src/main/java/com/back/fairytale/domain/user/entity/User.java
- backend/src/main/java/com/back/fairytale/global/security/CustomAuthenticationEntryPoint.java
- backend/src/main/java/com/back/fairytale/global/security/JWTProvider.java
- backend/src/main/java/com/back/fairytale/global/security/OAuth2LoginSuccessHandler.java
- backend/src/main/java/com/back/fairytale/global/security/SecurityConfig.java
- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-prod.yml
- backend/src/main/resources/application-test.yml
- frontend/src/app/fairytale/post/page.tsx
- 로그인을 해야 API 접근이 가능하도록 수정하였습니다.
- 쿠키 설정을 개발, 상용 환경으로 구분하였습니다.
- API 접근 시 인증이 안되었을 경우 401 응답을 반환하도록 하였습니다.
- 로그인 성공 후 액세스 토큰을 제외하고 리프레시 토큰만 반환하도록 수정하였습니다.
Close #115
> [Feat] API 접근 권한 설정

- backend/src/main/java/com/back/fairytale/global/security/CorsProperties.java
- backend/src/main/java/com/back/fairytale/global/security/SecurityConfig.java
- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-prod.yml
- 개발, 운영 환경 별로 CORS 설정을 분리하였습니다.
Close #133
> [Feat]: Cors 환경 별로 설정 분리

- frontend/src/app/clientLayout.tsx
- frontend/src/app/introduction/page.tsx
Close #143 
소개페이지와 레이아웃헤더 UI를 수정했습니다.
소개페이지: 문구를 좀 더 자연스럽게 수정하고, 컴포넌트간 간격을 조정하였습니다.
레이아웃 헤더: 헤더의 높이를 수정하였습니다.
> refactor: 소개페이지와 레이아웃헤더 UI마이너수정

- frontend/src/app/fairytale/post/page.tsx
1. 실시간 검증 기능 - 타이핑할때마다 실시간 검증 , 올바른 입력시 성공 표시 , 아닐시 에러메시지
2.키워드 중복 검사 기능 - 같은 키워드 추가 방지 , 실시간 중복 검사 , 추가할시 "이미 추가된 키워드입니다" 에러메시지
> 키워드 중복검사 , 실시간 검증 등 기능 추가

- backend/src/main/java/com/back/fairytale/domain/fairytale/entity/Fairytale.java
- backend/src/main/java/com/back/fairytale/domain/fairytale/repository/FairytaleRepository.java
- backend/src/main/java/com/back/fairytale/domain/like/controller/LikeController.java
- backend/src/main/java/com/back/fairytale/domain/like/service/LikeService.java
> [feat] 좋아요 동시성 문제 처리

- backend/src/main/java/com/back/fairytale/domain/user/controller/UserController.java
- backend/src/main/java/com/back/fairytale/global/security/SecurityConfig.java
> feat : 로그인 상태 조회용 API 구현

- backend/src/main/java/com/back/fairytale/domain/childThoughts/entity/ChildThoughts.java
Close #162 
아이생각기록 Entity를 구현하였습니다.
> feat: 아이이생각기록 Entity 구현

- frontend/src/app/clientLayout.tsx
- frontend/src/utils/customFetch.ts
Close #165 
백엔드에 로그인상태확인api가 추가되어 프론트엔드에서 로그인시 fetch하는 api를 변경하였습니다.
1. 로그인시 fetch하는 api를 변경하였습니다.
2. 위 코드수정에 따른 로그아웃시 발생하는 콘솔에러를 수정하였습니다.
> fix: 로그인 상태확인 연결api변경

- backend/src/main/java/com/back/fairytale/domain/fairytale/controller/FairytaleController.java
- backend/src/main/java/com/back/fairytale/domain/fairytale/dto/FairytaleListResponse.java
- backend/src/main/java/com/back/fairytale/domain/fairytale/dto/FairytalePublicListResponse.java
- backend/src/main/java/com/back/fairytale/domain/fairytale/repository/FairytaleRepository.java
- backend/src/main/java/com/back/fairytale/domain/fairytale/service/FairytaleService.java
- backend/src/main/java/com/back/fairytale/global/security/SecurityConfig.java
- frontend/src/app/fairytaleGallery/page.tsx
> [Feat]모든 동화 조회하는 API구현

- backend/src/main/java/com/back/fairytale/domain/fairytale/service/FairytaleService.java
- frontend/src/app/fairytale/get/[id]/page.tsx
- frontend/src/app/fairytale/get/page.tsx
Close #156 
동화 전체 목록 조회, 동화 상세 조회 모두 이미지도 조회되도록 수정하였습니다.
> 프론트엔드 동화 조회 이미지 추가

- backend/src/test/java/com/back/fairytale/domain/user/controller/UserControllerTest.java
> [Refactor] : UserController 테스트 코드 수정 및 사용자 정보 조회 테스트 추가

- backend/src/main/java/com/back/fairytale/domain/fairytale/controller/FairytaleController.java
- backend/src/main/java/com/back/fairytale/domain/fairytale/repository/FairytaleRepository.java
- backend/src/main/java/com/back/fairytale/domain/fairytale/service/FairytaleService.java
- frontend/src/app/fairytaleGallery/page.tsx
-  갤러리에서 6개씩 동화 페이징 표시
-  공개된 동화만 갤러리에 표시
-  중복 코드 제거로 코드 정리
> 갤러리 페이징 기능 구현 및 API 엔드포인트 정리

- frontend/src/app/clientLayout.tsx
> [Feat] 로그인 실패 시 팝업창에 문구 추가

- frontend/src/app/fairytale/gallery/[id]/page.tsx
- frontend/src/app/fairytaleGallery/page.tsx
- 동화 갤러리 페이지 표시
- 페이징 (6개씩, 다음/이전 페이지)
- 동화 클릭 시 상세 내용 보기
- 좋아요 버튼 클릭 시 즉시 반영
- 에러 메시지 변경 ( 아직 공개된 동화가 없습니다.)
> 동화 갤러리 페이지 수정

- backend/src/main/java/com/back/fairytale/domain/fairytale/entity/Fairytale.java
- backend/src/main/java/com/back/fairytale/domain/thoughts/controller/ThoughtsController.java
- backend/src/main/java/com/back/fairytale/domain/thoughts/repository/ThoughtsRepository.java
- backend/src/main/java/com/back/fairytale/domain/thoughts/service/ThoughtsService.java
- frontend/src/app/clientLayout.tsx
- frontend/src/app/fairytale/get/[id]/page.tsx
Close #178
프론트엔드 아이생각 기록 구현
키워드 보기 밑에 버튼을 둬서 팝업 형태로 아이생각과 부모생각을 기록하도록
> 프론트엔드 아이생각 구현

- backend/src/main/java/com/back/fairytale/domain/fairytale/service/FairytaleService.java
- backend/src/main/java/com/back/fairytale/global/util/CloudStorage.java
- backend/src/main/java/com/back/fairytale/global/util/impl/GoogleCloudStorage.java
Close #212 
* 이미지 업로드 부분에서 uploadImageBytesToCloud 약간 uploadImageToCloud랑 비슷한 동작을 사용해서 uploadImageBytesToCloud 제거하고 일원화 하기 위해 fairytale의 byte[] imageData를 MultipartFile 형식으로 수정
* 문제 생기면 말씀 부탁드립니다!
> [Refactor] 이미지 업로드 리팩토링

- backend/src/main/java/com/back/fairytale/domain/fairytale/entity/Fairytale.java
- 좋아요 기능 정상 작동
- null 상태에서도 안전하게 처리
- 음수 값 방지
> 좋아요 눌렀을때 반영되지않는 문제 해결

- frontend/src/app/fairytaleGallery/page.tsx
-좋아요 상태 유지 문제 해결
-좋아요 개수 표시 기능 추가
참고사항
-서버에서 likeCount 필드 추가 시 자동으로 개수 표시됨
> 좋아요 기능 새로고침 후 유지 안되는 문제 + 좋아요 개수 표시

- frontend/src/app/fairytale/gallery/[id]/page.tsx
- frontend/src/app/fairytale/get/[id]/page.tsx
- frontend/src/app/fairytale/get/page.tsx
- frontend/src/app/fairytaleGallery/comments.tsx
- frontend/src/app/fairytaleGallery/page.tsx
Close #194
프론트엔드에 댓글 UI를 구현하고 백엔드와 연결하였습니다.
동화조회페이지에서 공개/비공개설정을 할 수 있도록 기능을 추가하였습니다.
> [Feat] 댓글 UI구현 및 백엔드 연결 / 동화조회페이지 공개비공개설정기능추가

- backend/src/main/java/com/back/fairytale/domain/fairytale/dto/FairytalePublicListResponse.java
> 좋아요 개수 표시 기능 구현

- frontend/src/app/clientLayout.tsx
- frontend/src/app/fairytale/gallery/[id]/page.tsx
- frontend/src/app/fairytale/gallery/comments.tsx
- frontend/src/app/fairytale/gallery/page.tsx
Close #226 
댓글 페이징 기능을 구현하고, 리팩토링과 UI 개선을 하였습니다.
1. 동화갤러리 프론트엔드코드를 리팩토링하고, UI를 개선하였습니다.
2. 프론트엔드 댓글 페이징 기능을 추가하였습니다.
> [Feat] 프론트엔드 댓글 페이징 기능 구현

- frontend/src/app/clientLayout.tsx
- frontend/src/app/fairytale/gallery/[id]/page.tsx
- frontend/src/app/fairytale/gallery/comments.tsx
- frontend/src/app/fairytale/gallery/page.tsx
- frontend/src/app/fairytale/get/[id]/page.tsx
- frontend/src/app/introduction/page.tsx
- frontend/src/utils/customFetch.ts
> [Fix] 타입스크립트 에러 수정

- backend/src/main/resources/application.yml
- frontend/src/app/clientLayout.tsx
- frontend/src/app/fairytale/gallery/[id]/page.tsx
- frontend/src/app/fairytale/gallery/comments.tsx
- frontend/src/app/fairytale/gallery/page.tsx
- frontend/src/app/fairytale/get/[id]/page.tsx
- frontend/src/app/fairytale/get/page.tsx
- frontend/src/app/fairytale/post/page.tsx
- frontend/src/utils/customFetch.ts
> [Feat] 서버 클라 연동
